#!/bin/sh
file=modification_time.txt
tmpfile=/tmp/$$.txt
line="line"
find foo > $tmpfile
cat /dev/null > $file
cat $tmpfile | while read line
do
	echo $line >> $file
	stat -c %y $line >> $file
done
git add $file
cat /dev/null > $file
rm -f $tmpfile
