#!/bin/sh
file=modification_time.txt
tmpfile=/tmp/$$.txt
line="line"
git status -s > $tmpfile
sed -E -i "s/[AM]+ +//" $tmpfile
sed -E -i "/^\?+/d" $tmpfile
sed -E -i "/^D/d" $tmpfile
sed -E -i "^ +/d" $tmpfile
sed -E -i "/^R/s/^R.*-> //" $tmpfile
cat /dev/null > $file
cat $tmpfile | while read line
do
	echo $line >> $file
	stat -c %y $line >> $file
done
git add $file

